const PRODUCT_IMAGES = import.meta.glob('./*.jpg', {
  eager: true,
  import: 'default',
}) as Record<string, string>;

export const productImage = (filename: string) => PRODUCT_IMAGES[`./${filename}`];

export const PRODUCTS = [
  {
    id: 1,
    name: 'Rower szosowy',
    price: 89,
    image: productImage('01-road-bike.jpg'),
    alt: 'Rower szosowy',
    category: 'Rowery i akcesoria',
  },
  {
    id: 2,
    name: 'Rower górski MTB',
    price: 99,
    image: productImage('02-mountain-bike.jpg'),
    alt: 'Rower górski MTB',
    category: 'Rowery i akcesoria',
  },
  {
    id: 3,
    name: 'Kask rowerowy',
    price: 25,
    image: productImage('03-bike-helmet.jpg'),
    alt: 'Kask rowerowy',
    category: 'Rowery i akcesoria',
  },
  {
    id: 4,
    name: 'Przyczepka rowerowa dla dzieci',
    price: 65,
    image: productImage('04-child-bike-trailer.jpg'),
    alt: 'Przyczepka rowerowa dla dzieci',
    category: 'Przyczepki rowerowe',
  },
  {
    id: 5,
    name: 'Przyczepka rowerowa bagażowa',
    price: 49,
    image: productImage('05-cargo-bike-trailer.jpg'),
    alt: 'Przyczepka rowerowa bagażowa',
    category: 'Przyczepki rowerowe',
  },
  {
    id: 6,
    name: 'Przyczepka rowerowa dla psa',
    price: 55,
    image: productImage('06-dog-bike-trailer.jpg'),
    alt: 'Przyczepka rowerowa dla psa',
    category: 'Przyczepki rowerowe',
  },
  {
    id: 7,
    name: 'Namiot dwuosobowy',
    price: 45,
    image: productImage('07-two-person-tent.jpg'),
    alt: 'Namiot dwuosobowy',
    category: 'Namioty osobowe',
  },
  {
    id: 8,
    name: 'Namiot trzyosobowy',
    price: 59,
    image: productImage('08-three-person-tent.jpg'),
    alt: 'Namiot trzyosobowy',
    category: 'Namioty osobowe',
  },
  {
    id: 9,
    name: 'Namiot czteroosobowy',
    price: 75,
    image: productImage('09-four-person-tent.jpg'),
    alt: 'Namiot czteroosobowy',
    category: 'Namioty osobowe',
  },
  {
    id: 10,
    name: 'Deska SUP',
    price: 79,
    image: productImage('10-sup-board.jpg'),
    alt: 'Deska SUP',
    category: 'Sprzęt wodny',
  },
  {
    id: 11,
    name: 'Kajak dwuosobowy',
    price: 119,
    image: productImage('11-two-person-kayak.jpg'),
    alt: 'Kajak dwuosobowy',
    category: 'Sprzęt wodny',
  },
  {
    id: 12,
    name: 'Kamizelka asekuracyjna',
    price: 20,
    image: productImage('12-life-jacket.jpg'),
    alt: 'Kamizelka asekuracyjna',
    category: 'Sprzęt wodny',
  },
  {
    id: 13,
    name: 'Zestaw via ferrata',
    price: 49,
    image: productImage('13-via-ferrata-set.jpg'),
    alt: 'Zestaw via ferrata',
    category: 'Via ferraty i wspinanie',
  },
  {
    id: 14,
    name: 'Uprząż wspinaczkowa',
    price: 35,
    image: productImage('14-climbing-harness.jpg'),
    alt: 'Uprząż wspinaczkowa',
    category: 'Via ferraty i wspinanie',
  },
  {
    id: 15,
    name: 'Kask wspinaczkowy',
    price: 29,
    image: productImage('15-climbing-helmet.jpg'),
    alt: 'Kask wspinaczkowy',
    category: 'Via ferraty i wspinanie',
  },
  {
    id: 16,
    name: 'Nosidełko turystyczne dla dziecka',
    price: 69,
    image: productImage('16-child-carrier.jpg'),
    alt: 'Nosidełko turystyczne dla dziecka',
    category: 'Nosidełka turystyczne',
  },
  {
    id: 17,
    name: 'Lekkie nosidełko turystyczne',
    price: 55,
    image: productImage('17-light-child-carrier.jpg'),
    alt: 'Lekkie nosidełko turystyczne',
    category: 'Nosidełka turystyczne',
  },
  {
    id: 18,
    name: 'Namiot rodzinny',
    price: 109,
    image: productImage('18-family-tent.jpg'),
    alt: 'Namiot rodzinny',
    category: 'Namioty',
  },
  {
    id: 19,
    name: 'Namiot kempingowy',
    price: 85,
    image: productImage('19-camping-tent.jpg'),
    alt: 'Namiot kempingowy',
    category: 'Namioty',
  },
  {
    id: 20,
    name: 'Namiot dachowy',
    price: 179,
    image: productImage('20-rooftop-tent.jpg'),
    alt: 'Namiot dachowy',
    category: 'Namioty',
  },
  {
    id: 21,
    name: 'Rower miejski',
    price: 69,
    image: productImage('21-city-bike.jpg'),
    alt: 'Rower miejski',
    category: 'Rowery i akcesoria',
  },
  {
    id: 22,
    name: 'Rower elektryczny',
    price: 149,
    image: productImage('22-electric-bike.jpg'),
    alt: 'Rower elektryczny',
    category: 'Rowery i akcesoria',
  },
  {
    id: 23,
    name: 'Sakwy rowerowe',
    price: 29,
    image: productImage('23-bike-panniers.jpg'),
    alt: 'Sakwy rowerowe',
    category: 'Rowery i akcesoria',
  },
  {
    id: 24,
    name: 'Jednokołowa przyczepka rowerowa',
    price: 59,
    image: productImage('24-single-wheel-trailer.jpg'),
    alt: 'Jednokołowa przyczepka rowerowa',
    category: 'Przyczepki rowerowe',
  },
  {
    id: 25,
    name: 'Składana przyczepka rowerowa',
    price: 54,
    image: productImage('25-folding-bike-trailer.jpg'),
    alt: 'Składana przyczepka rowerowa',
    category: 'Przyczepki rowerowe',
  },
  {
    id: 26,
    name: 'Namiot trekkingowy',
    price: 64,
    image: productImage('26-touring-tent.jpg'),
    alt: 'Namiot trekkingowy',
    category: 'Namioty osobowe',
  },
  {
    id: 27,
    name: 'Namiot zimowy',
    price: 99,
    image: productImage('27-winter-tent.jpg'),
    alt: 'Namiot zimowy',
    category: 'Namioty osobowe',
  },
  {
    id: 28,
    name: 'Kajak dmuchany',
    price: 89,
    image: productImage('28-inflatable-kayak.jpg'),
    alt: 'Kajak dmuchany',
    category: 'Sprzęt wodny',
  },
  {
    id: 29,
    name: 'Kanadyjka dwuosobowa',
    price: 109,
    image: productImage('29-canoe.jpg'),
    alt: 'Kanadyjka dwuosobowa',
    category: 'Sprzęt wodny',
  },
  {
    id: 30,
    name: 'Wiosło kajakowe',
    price: 19,
    image: productImage('30-kayak-paddle.jpg'),
    alt: 'Wiosło kajakowe',
    category: 'Sprzęt wodny',
  },
  {
    id: 31,
    name: 'Lina wspinaczkowa 60 m',
    price: 39,
    image: productImage('31-climbing-rope.jpg'),
    alt: 'Lina wspinaczkowa',
    category: 'Via ferraty i wspinanie',
  },
  {
    id: 32,
    name: 'Zestaw karabinków wspinaczkowych',
    price: 24,
    image: productImage('32-carabiner-set.jpg'),
    alt: 'Zestaw karabinków wspinaczkowych',
    category: 'Via ferraty i wspinanie',
  },
  {
    id: 33,
    name: 'Buty wspinaczkowe',
    price: 34,
    image: productImage('33-climbing-shoes.jpg'),
    alt: 'Buty wspinaczkowe',
    category: 'Via ferraty i wspinanie',
  },
  {
    id: 34,
    name: 'Nosidełko turystyczne premium',
    price: 79,
    image: productImage('34-hiking-carrier.jpg'),
    alt: 'Nosidełko turystyczne premium',
    category: 'Nosidełka turystyczne',
  },
  {
    id: 35,
    name: 'Nosidełko z osłoną przeciwdeszczową',
    price: 74,
    image: productImage('35-rain-cover-carrier.jpg'),
    alt: 'Nosidełko z osłoną przeciwdeszczową',
    category: 'Nosidełka turystyczne',
  },
  {
    id: 36,
    name: 'Namiot tunelowy',
    price: 119,
    image: productImage('36-tunnel-tent.jpg'),
    alt: 'Namiot tunelowy',
    category: 'Namioty',
  },
  {
    id: 37,
    name: 'Namiot samorozkładający',
    price: 49,
    image: productImage('37-pop-up-tent.jpg'),
    alt: 'Namiot samorozkładający',
    category: 'Namioty',
  },
  {
    id: 38,
    name: 'Namiot ekspedycyjny',
    price: 139,
    image: productImage('38-expedition-tent.jpg'),
    alt: 'Namiot ekspedycyjny',
    category: 'Namioty',
  },
  {
    id: 39,
    name: 'Zestaw naprawczy do roweru',
    price: 18,
    image: productImage('39-bike-repair-kit.jpg'),
    alt: 'Zestaw naprawczy do roweru',
    category: 'Rowery i akcesoria',
  },
  {
    id: 40,
    name: 'Wodoodporny worek transportowy',
    price: 22,
    image: productImage('40-waterproof-bag.jpg'),
    alt: 'Wodoodporny worek transportowy',
    category: 'Sprzęt wodny',
  },
];
